version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: txs-crafty_crafty_1
      APP_PORT: 8443
      PROXY_AUTH_ADD: "false"

  crafty:
    image: registry.gitlab.com/crafty-controller/crafty-4:4.10.8
    restart: on-failure
    stop_grace_period: 1m

    environment:
      TZ: Europe/Berlin

    ports:
      # Bedrock
      - "19132:19132/udp"

      # Minecraft Java Server
      - "25500-25600:25500-25600"

      # Crafty Dynmap
      # außen 8523, innen 8123
      - "8523:8123"

    volumes:
      - ${APP_DATA_DIR}/backups:/crafty/backups
      - ${APP_DATA_DIR}/logs:/crafty/logs
      - ${APP_DATA_DIR}/servers:/crafty/servers
      - ${APP_DATA_DIR}/config:/crafty/app/config
      - ${APP_DATA_DIR}/import:/crafty/import
