services:

  app_proxy:
    environment:
      APP_HOST: txs-crafty_crafty_1
      APP_PORT: 8443
      PROXY_AUTH_ADD: "false"

  crafty:
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always

    environment:
      TZ: Europe/Berlin
  
  ports:
    - "19132:19132/udp"
    - "25500-25600:25500-25600"

    volumes:
      - ${APP_DATA_DIR}/backups:/crafty/backups
      - ${APP_DATA_DIR}/logs:/crafty/logs
      - ${APP_DATA_DIR}/servers:/crafty/servers
      - ${APP_DATA_DIR}/config:/crafty/app/config
      - ${APP_DATA_DIR}/import:/crafty/import
