version: "3.7"

services:

  crafty:
    image: registry.gitlab.com/crafty-controller/crafty-4:4.10.7
    restart: on-failure
    stop_grace_period: 1m

    environment:
      TZ: Europe/Berlin

    ports:
      # Crafty Webinterface (HTTPS)
      - "8443:8443"

      # Dynmap
      - "8523:8123"

      # Bedrock
      - "19132:19132/udp"

      # Minecraft Java
      - "25500-25600:25500-25600"

    volumes:
      - ${APP_DATA_DIR}/backups:/crafty/backups
      - ${APP_DATA_DIR}/logs:/crafty/logs
      - ${APP_DATA_DIR}/servers:/crafty/servers
      - ${APP_DATA_DIR}/config:/crafty/app/config
      - ${APP_DATA_DIR}/import:/crafty/import
